version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    build: ./backend
    ports:
      # local->container
      - 8080:8080
    environment:
      PORT: 8080
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: sample-db
    depends_on: 
      - mongo_db
  
  # ui service
  ui:
    build: ./frontend
    ports:
      # local->container
      - 9080:9080
    environment:
      PORT: 9080
      API_URL: http://api:8080
    depends_on: 
      - api

volumes:
  mongo_data: {}